Pet Gotchis
OriumNetwork/orium-aavegotchi-operator pull request #1
Opened 2022-07-27 19:11 UTC by ernanirst

The first version of the Orium Aavegotchi Operator should enable anyone to add/remove their own address to the list and expose a function that pets all the gotchis. Users might also revoke petting permission. For this reason, the petting function might remove addresses that have done so.

2022-07-27 20:33 UTC, danielnovy commented on contracts/AavegotchiOperator.sol
> +    constructor(address _aavegotchiDiamondContract) payable {
Why is this contructor payable? Also, wouldn't it be better to store the address for the contract instead of the contract instantiated? This way, if it changes we can easily update on our side.

2022-07-27 20:33 UTC, danielnovy commented on contracts/AavegotchiOperator.sol
> +            uint32[] memory nftIds = tokenIdsPerAddress[i];
I believe we can save a lot of gas by using just one "for" iteration. What this second "for" is doing can be put in the first "for", no?

2022-07-27 20:33 UTC, danielnovy commented on contracts/AavegotchiOperator.sol
> +        for (uint256 i; i < approvedAddresses.length; i++) {
Same comment as before: can't we use the previous "for" for doing everything in just one iteration?

2022-07-29 13:00 UTC, ernanirst commented on contracts/AavegotchiOperator.sol
> +    EnumerableSet.AddressSet private _approvedAddresses;
Structs and arrays cannot be public in solidity

2022-07-29 13:01 UTC, ernanirst commented on contracts/AavegotchiOperator.sol
> +    constructor(address _aavegotchiDiamondContract) payable {
fixed

2022-07-29 13:02 UTC, ernanirst commented on contracts/AavegotchiOperator.sol
> +            uint32[] memory nftIds = tokenIdsPerAddress[i];
Split function in two. The read-only function will now generate two arrays that the transaction will use.

2022-07-29 13:02 UTC, ernanirst commented on contracts/AavegotchiOperator.sol
> +        for (uint256 i; i < approvedAddresses.length; i++) {
Split function in two. The read-only function will now generate two arrays that the transaction will use.

2022-07-29 13:57 UTC, danielnovy requested changes

2022-07-29 13:57 UTC, danielnovy commented on contracts/AavegotchiOperator.sol
> +    function petAavegotchisAndRemoveRevoked(uint256[] calldata tokenIds, address[] calldata revokedAddresses) external {
This function should have a execution restriction (ex: onlyAdmins) since a bad actor could keep calling it to remove all addresses and make this contract useless.

2022-07-29 13:57 UTC, danielnovy commented on contracts/AavegotchiOperator.sol
> +    address public _aavegotchiDiamondAddress;
There should be a function to update this address. This function should only be allowed by admins of this contract, which also brings the case that there should be an admin (or owner) of this contract (see comment below).

2022-07-29 14:34 UTC, ernanirst commented on contracts/AavegotchiOperator.sol
> +    function petAavegotchisAndRemoveRevoked(uint256[] calldata tokenIds, address[] calldata revokedAddresses) external {
Decided to address in a new PR

2022-07-29 14:35 UTC, ernanirst commented on contracts/AavegotchiOperator.sol
> +    address public _aavegotchiDiamondAddress;
Decided to address in a new PR

2022-07-29 14:37 UTC, danielnovy approved these changes
Sounds fair. Let's do it when the gelato PR is created.

2022-07-29 14:39 UTC, merged